### ISSUE TITLE
please update camera-cube-env.js for aframe 0.9.0

### ISSUE THREAD

**Issue by comsyspro** [colinfizgig/Parthenon_Project#16]
I detected some problematic issues with your **camera-cube-env.js** component in combination with aframe 0.9.0.

The first console log error I got is:

> .getWorldPosition() target is now required

That could be fixed with:
```
Line 58:
AFRAME.scenes[0].renderer.autoClear = true;
var target = new THREE.Vector3();
myCam.position.copy(this.el.object3D.worldToLocal(this.el.object3D.getWorldPosition(target)));
```
But the other log error shows the following:

> RENDER WARNING: texture bound to texture unit 2 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.

And here I didn't find a solution to fix this. So can you please look into this issue and can you update the script for aframe 0.9.0 version.

Thanks.

**Comment by colinfizgig** [comment]
I’m aware of the issue.  The main part I find causing it is setting the mipmap property. If I take this out it works but it seems that setting the roughness property on the material is broken then. The material won’t get rougher.  So I’m trying to figure out how to force mipmapping in order to allow dull reflections

**Comment by comsyspro** [comment]
Thanks to your answer I could now get it work by setting this as follow:

`this.cam.renderTarget.texture.generateMipmaps = true;`

Also the roughness works.

**Comment by colinfizgig** [comment]
Thanks for the feedback. I’ll update the component.

**Comment by colinfizgig** [comment]
Where are you placing the

this.cam.renderTarget.texture.generateMipmaps = true;

I'm trying to edit the component and I'm not seeing roughness update when I
add that to the code.

**Comment by comsyspro** [comment]
I added this on the line 24 (init) and also on line 92 (update) and it works. Also the roughness works with different values.

**Comment by colinfizgig** [comment]
It appears That the roughness is not updating.  On my test scene the sphere stays sharp while the specular hilight does not with a roughness set to 0.3.  In the previous version of aframe this would blur the mipmaps creating a blurred result.  However just setting generateMipmaps to true does not seem to create the actual mipmaps.  See the included image
![Broken Roughness](https://user-images.githubusercontent.com/7503097/55254332-f3df1480-522d-11e9-8857-1d1511da26cf.JPG)

**Comment by colinfizgig** [comment]
It seems to be an issue with three.js WebGL.rendertargets not updating after parameters are set.

https://github.com/mrdoob/three.js/issues/14375

I'll keep working on a way to set them.

**Comment by comsyspro** [comment]
![screenshot](https://user-images.githubusercontent.com/13809377/55272231-b758fa80-52b9-11e9-8c64-79e6bc533aa9.JPG)

With the mentioned changes in the code all works fine for me with the roughness. Even the 25000 grass meshes are reflected.

**Comment by colinfizgig** [comment]
Thanks for that.  I was editing the code in my components github.  I must have broke something.  I tried editing the one in this Git and it worked.  Not sure what I was breaking in the original.  I'll update both with the fixed code.
